// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyVet.Web.Data;

namespace MyVet.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200126202512_SeedAll")]
    partial class SeedAll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyVet.Web.Data.Entities.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsAvailable");

                    b.Property<int?>("OwnerId");

                    b.Property<int?>("PetId");

                    b.Property<string>("Remarks");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetId");

                    b.ToTable("Agendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 1, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 1, 27, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 1, 27, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 1, 27, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 1, 27, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2020, 1, 28, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2020, 1, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2020, 1, 28, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2020, 1, 28, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2020, 1, 28, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2020, 1, 29, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2020, 1, 29, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2020, 1, 29, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2020, 1, 29, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2020, 1, 29, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2020, 1, 30, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2020, 1, 30, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2020, 1, 30, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2020, 1, 30, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2020, 1, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2020, 1, 31, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2020, 1, 31, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2020, 1, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2020, 1, 31, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2020, 1, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2020, 2, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2020, 2, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2020, 2, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2020, 2, 1, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2020, 2, 1, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2020, 2, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2020, 2, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2020, 2, 3, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2020, 2, 3, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2020, 2, 3, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2020, 2, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2020, 2, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2020, 2, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2020, 2, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2020, 2, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2020, 2, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2020, 2, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2020, 2, 5, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2020, 2, 5, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2020, 2, 5, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2020, 2, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2020, 2, 6, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2020, 2, 6, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2020, 2, 6, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2020, 2, 6, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2020, 2, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2020, 2, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2020, 2, 7, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2020, 2, 7, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2020, 2, 7, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2020, 2, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2020, 2, 8, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2020, 2, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2020, 2, 8, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2020, 2, 8, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2020, 2, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2020, 2, 10, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2020, 2, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2020, 2, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2020, 2, 10, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2020, 2, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2020, 2, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2020, 2, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2020, 2, 11, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2020, 2, 11, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2020, 2, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2020, 2, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2020, 2, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2020, 2, 12, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2020, 2, 12, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2020, 2, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2020, 2, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2020, 2, 13, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2020, 2, 13, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2020, 2, 13, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2020, 2, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2020, 2, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2020, 2, 14, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2020, 2, 14, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2020, 2, 14, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2020, 2, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2020, 2, 15, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2020, 2, 15, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2020, 2, 15, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2020, 2, 15, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTime(2020, 2, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTime(2020, 2, 17, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTime(2020, 2, 17, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 94,
                            Date = new DateTime(2020, 2, 17, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 95,
                            Date = new DateTime(2020, 2, 17, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 96,
                            Date = new DateTime(2020, 2, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 97,
                            Date = new DateTime(2020, 2, 18, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 98,
                            Date = new DateTime(2020, 2, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 99,
                            Date = new DateTime(2020, 2, 18, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 100,
                            Date = new DateTime(2020, 2, 18, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 101,
                            Date = new DateTime(2020, 2, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 102,
                            Date = new DateTime(2020, 2, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 103,
                            Date = new DateTime(2020, 2, 19, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 104,
                            Date = new DateTime(2020, 2, 19, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 105,
                            Date = new DateTime(2020, 2, 19, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 106,
                            Date = new DateTime(2020, 2, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 107,
                            Date = new DateTime(2020, 2, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 108,
                            Date = new DateTime(2020, 2, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 109,
                            Date = new DateTime(2020, 2, 20, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 110,
                            Date = new DateTime(2020, 2, 20, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 111,
                            Date = new DateTime(2020, 2, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 112,
                            Date = new DateTime(2020, 2, 21, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 113,
                            Date = new DateTime(2020, 2, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 114,
                            Date = new DateTime(2020, 2, 21, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 115,
                            Date = new DateTime(2020, 2, 21, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 116,
                            Date = new DateTime(2020, 2, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 117,
                            Date = new DateTime(2020, 2, 22, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 118,
                            Date = new DateTime(2020, 2, 22, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 119,
                            Date = new DateTime(2020, 2, 22, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 120,
                            Date = new DateTime(2020, 2, 22, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 121,
                            Date = new DateTime(2020, 2, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 122,
                            Date = new DateTime(2020, 2, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 123,
                            Date = new DateTime(2020, 2, 24, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 124,
                            Date = new DateTime(2020, 2, 24, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 125,
                            Date = new DateTime(2020, 2, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 126,
                            Date = new DateTime(2020, 2, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 127,
                            Date = new DateTime(2020, 2, 25, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 128,
                            Date = new DateTime(2020, 2, 25, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 129,
                            Date = new DateTime(2020, 2, 25, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 130,
                            Date = new DateTime(2020, 2, 25, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 131,
                            Date = new DateTime(2020, 2, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 132,
                            Date = new DateTime(2020, 2, 26, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 133,
                            Date = new DateTime(2020, 2, 26, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 134,
                            Date = new DateTime(2020, 2, 26, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 135,
                            Date = new DateTime(2020, 2, 26, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 136,
                            Date = new DateTime(2020, 2, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 137,
                            Date = new DateTime(2020, 2, 27, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 138,
                            Date = new DateTime(2020, 2, 27, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 139,
                            Date = new DateTime(2020, 2, 27, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 140,
                            Date = new DateTime(2020, 2, 27, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 141,
                            Date = new DateTime(2020, 2, 28, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 142,
                            Date = new DateTime(2020, 2, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 143,
                            Date = new DateTime(2020, 2, 28, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 144,
                            Date = new DateTime(2020, 2, 28, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 145,
                            Date = new DateTime(2020, 2, 28, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 146,
                            Date = new DateTime(2020, 2, 29, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 147,
                            Date = new DateTime(2020, 2, 29, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 148,
                            Date = new DateTime(2020, 2, 29, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 149,
                            Date = new DateTime(2020, 2, 29, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 150,
                            Date = new DateTime(2020, 2, 29, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 151,
                            Date = new DateTime(2020, 3, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 152,
                            Date = new DateTime(2020, 3, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 153,
                            Date = new DateTime(2020, 3, 2, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 154,
                            Date = new DateTime(2020, 3, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 155,
                            Date = new DateTime(2020, 3, 2, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 156,
                            Date = new DateTime(2020, 3, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 157,
                            Date = new DateTime(2020, 3, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 158,
                            Date = new DateTime(2020, 3, 3, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 159,
                            Date = new DateTime(2020, 3, 3, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 160,
                            Date = new DateTime(2020, 3, 3, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 161,
                            Date = new DateTime(2020, 3, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 162,
                            Date = new DateTime(2020, 3, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 163,
                            Date = new DateTime(2020, 3, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 164,
                            Date = new DateTime(2020, 3, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 165,
                            Date = new DateTime(2020, 3, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 166,
                            Date = new DateTime(2020, 3, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 167,
                            Date = new DateTime(2020, 3, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 168,
                            Date = new DateTime(2020, 3, 5, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 169,
                            Date = new DateTime(2020, 3, 5, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 170,
                            Date = new DateTime(2020, 3, 5, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 171,
                            Date = new DateTime(2020, 3, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 172,
                            Date = new DateTime(2020, 3, 6, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 173,
                            Date = new DateTime(2020, 3, 6, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 174,
                            Date = new DateTime(2020, 3, 6, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 175,
                            Date = new DateTime(2020, 3, 6, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 176,
                            Date = new DateTime(2020, 3, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 177,
                            Date = new DateTime(2020, 3, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 178,
                            Date = new DateTime(2020, 3, 7, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 179,
                            Date = new DateTime(2020, 3, 7, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 180,
                            Date = new DateTime(2020, 3, 7, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 181,
                            Date = new DateTime(2020, 3, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 182,
                            Date = new DateTime(2020, 3, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 183,
                            Date = new DateTime(2020, 3, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 184,
                            Date = new DateTime(2020, 3, 9, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 185,
                            Date = new DateTime(2020, 3, 9, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 186,
                            Date = new DateTime(2020, 3, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 187,
                            Date = new DateTime(2020, 3, 10, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 188,
                            Date = new DateTime(2020, 3, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 189,
                            Date = new DateTime(2020, 3, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 190,
                            Date = new DateTime(2020, 3, 10, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 191,
                            Date = new DateTime(2020, 3, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 192,
                            Date = new DateTime(2020, 3, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 193,
                            Date = new DateTime(2020, 3, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 194,
                            Date = new DateTime(2020, 3, 11, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 195,
                            Date = new DateTime(2020, 3, 11, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 196,
                            Date = new DateTime(2020, 3, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 197,
                            Date = new DateTime(2020, 3, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 198,
                            Date = new DateTime(2020, 3, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 199,
                            Date = new DateTime(2020, 3, 12, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 200,
                            Date = new DateTime(2020, 3, 12, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 201,
                            Date = new DateTime(2020, 3, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 202,
                            Date = new DateTime(2020, 3, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 203,
                            Date = new DateTime(2020, 3, 13, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 204,
                            Date = new DateTime(2020, 3, 13, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 205,
                            Date = new DateTime(2020, 3, 13, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 206,
                            Date = new DateTime(2020, 3, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 207,
                            Date = new DateTime(2020, 3, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 208,
                            Date = new DateTime(2020, 3, 14, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 209,
                            Date = new DateTime(2020, 3, 14, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 210,
                            Date = new DateTime(2020, 3, 14, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 211,
                            Date = new DateTime(2020, 3, 16, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 212,
                            Date = new DateTime(2020, 3, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 213,
                            Date = new DateTime(2020, 3, 16, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 214,
                            Date = new DateTime(2020, 3, 16, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 215,
                            Date = new DateTime(2020, 3, 16, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 216,
                            Date = new DateTime(2020, 3, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 217,
                            Date = new DateTime(2020, 3, 17, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 218,
                            Date = new DateTime(2020, 3, 17, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 219,
                            Date = new DateTime(2020, 3, 17, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 220,
                            Date = new DateTime(2020, 3, 17, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 221,
                            Date = new DateTime(2020, 3, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 222,
                            Date = new DateTime(2020, 3, 18, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 223,
                            Date = new DateTime(2020, 3, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 224,
                            Date = new DateTime(2020, 3, 18, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 225,
                            Date = new DateTime(2020, 3, 18, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 226,
                            Date = new DateTime(2020, 3, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 227,
                            Date = new DateTime(2020, 3, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 228,
                            Date = new DateTime(2020, 3, 19, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 229,
                            Date = new DateTime(2020, 3, 19, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 230,
                            Date = new DateTime(2020, 3, 19, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 231,
                            Date = new DateTime(2020, 3, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 232,
                            Date = new DateTime(2020, 3, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 233,
                            Date = new DateTime(2020, 3, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 234,
                            Date = new DateTime(2020, 3, 20, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 235,
                            Date = new DateTime(2020, 3, 20, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 236,
                            Date = new DateTime(2020, 3, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 237,
                            Date = new DateTime(2020, 3, 21, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 238,
                            Date = new DateTime(2020, 3, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 239,
                            Date = new DateTime(2020, 3, 21, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 240,
                            Date = new DateTime(2020, 3, 21, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 241,
                            Date = new DateTime(2020, 3, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 242,
                            Date = new DateTime(2020, 3, 23, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 243,
                            Date = new DateTime(2020, 3, 23, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 244,
                            Date = new DateTime(2020, 3, 23, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 245,
                            Date = new DateTime(2020, 3, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 246,
                            Date = new DateTime(2020, 3, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 247,
                            Date = new DateTime(2020, 3, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 248,
                            Date = new DateTime(2020, 3, 24, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 249,
                            Date = new DateTime(2020, 3, 24, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 250,
                            Date = new DateTime(2020, 3, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 251,
                            Date = new DateTime(2020, 3, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 252,
                            Date = new DateTime(2020, 3, 25, 16, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 253,
                            Date = new DateTime(2020, 3, 25, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 254,
                            Date = new DateTime(2020, 3, 25, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 255,
                            Date = new DateTime(2020, 3, 25, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            OwnerId = 1,
                            PetId = 1
                        });
                });

            modelBuilder.Entity("MyVet.Web.Data.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("PetId");

                    b.Property<string>("Remarks");

                    b.Property<int?>("ServiceTypeId");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("MyVet.Web.Data.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20);

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FixedPhone")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle Luna Calle Sol",
                            CellPhone = "310 322 3221",
                            Document = "8989898",
                            FirstName = "Juan",
                            FixedPhone = "234 3232",
                            LastName = "Zuluaga"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Calle 77 #22 21",
                            CellPhone = "300 322 3221",
                            Document = "7655544",
                            FirstName = "Jose",
                            FixedPhone = "343 3226",
                            LastName = "Cardona"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Carrera 56 #22 21",
                            CellPhone = "350 322 3221",
                            Document = "6565555",
                            FirstName = "Maria",
                            FixedPhone = "450 4332",
                            LastName = "López"
                        });
                });

            modelBuilder.Entity("MyVet.Web.Data.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Born");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("OwnerId");

                    b.Property<int?>("PetTypeId");

                    b.Property<string>("Race")
                        .HasMaxLength(50);

                    b.Property<string>("Remarks");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetTypeId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Born = new DateTime(2018, 1, 26, 14, 25, 9, 731, DateTimeKind.Local).AddTicks(2952),
                            Name = "Otto",
                            OwnerId = 1,
                            PetTypeId = 1,
                            Race = "Shih tzu"
                        },
                        new
                        {
                            Id = 2,
                            Born = new DateTime(2018, 1, 26, 14, 25, 9, 734, DateTimeKind.Local).AddTicks(5939),
                            Name = "Killer",
                            OwnerId = 2,
                            PetTypeId = 1,
                            Race = "Dobermann"
                        });
                });

            modelBuilder.Entity("MyVet.Web.Data.Entities.PetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("PetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Perro"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gato"
                        });
                });

            modelBuilder.Entity("MyVet.Web.Data.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Consulta"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Urgencia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vacunación"
                        });
                });

            modelBuilder.Entity("MyVet.Web.Data.Entities.Agenda", b =>
                {
                    b.HasOne("MyVet.Web.Data.Entities.Owner", "Owner")
                        .WithMany("Agendas")
                        .HasForeignKey("OwnerId");

                    b.HasOne("MyVet.Web.Data.Entities.Pet", "Pet")
                        .WithMany("Agendas")
                        .HasForeignKey("PetId");
                });

            modelBuilder.Entity("MyVet.Web.Data.Entities.History", b =>
                {
                    b.HasOne("MyVet.Web.Data.Entities.Pet", "Pet")
                        .WithMany("Histories")
                        .HasForeignKey("PetId");

                    b.HasOne("MyVet.Web.Data.Entities.ServiceType", "ServiceType")
                        .WithMany("Histories")
                        .HasForeignKey("ServiceTypeId");
                });

            modelBuilder.Entity("MyVet.Web.Data.Entities.Pet", b =>
                {
                    b.HasOne("MyVet.Web.Data.Entities.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId");

                    b.HasOne("MyVet.Web.Data.Entities.PetType", "PetType")
                        .WithMany("Pets")
                        .HasForeignKey("PetTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
